language: node_js
dist: trusty
sudo: required
node_js: stable
install:
  - npm install -g bower
  - npm install -g gulp
  - npm install
  - bower install
script:
  - gulp browserify
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
